# Generated by Django 3.0.3 on 2020-05-14 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(db_index=True, max_length=128)),
                ('sexo', models.CharField(max_length=1, null=True)),
                ('cpf', models.CharField(max_length=14, null=True, unique=True)),
                ('telefone', models.CharField(max_length=15, null=True)),
                ('endereco', models.TextField(max_length=512, null=True)),
                ('cep', models.CharField(max_length=10, null=True)),
                ('estado_uf', models.CharField(max_length=2, null=True)),
                ('cidade', models.CharField(max_length=64, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
